# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: YoungBin, KIM
title: AI Research
email: dudqls1994@ajou.ac.kr
phone: +82)010-8638-9316


# Social links
# twitter_username: jekyllrb
github_username:  dudqls1994
# dribbble_username: jekyll
facebook_username: profile.php?id=100003759608148
# flickr_username: jekyll
# instagram_username: duddbs2009/
linkedin_username: 영빈-김-942886137
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/yb2.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a student of graduate school of Ajou University and a member of [CVPR Lab](https://sites.google.com/site/haepaly/Home).     
  My recent research interests are in computer vision and deep learning.     
  In particular, I am interested in Quantize Neural Network and model compression.    
    
    - Computer Vision & Deep Learning
    - Quantize Neural Network 
    - Binary Neural Network
    - Model Compression
    
  And I am NNQ & CND Study member in AI-Robotics KR. You can see my presentation in YouTube.
  
  
  BNN+: Improved Binary Network Training[YouTube](https://www.youtube.com/watch?v=M7-lBoiFHRI&list=PLOhkE9VmM0SUh7J9NM8hnBol6R3CmqJFd&index=4) 
  & Bi-Real Nets(ECCV2018)[YouTube](https://www.youtube.com/watch?v=pQmvmcPZHmM)
  

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I am a student of graduate school of Ajou University and a member of CVPR Lab. 
  
  Please contact me for the detailed information. 

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
